# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Travail\EFS\Travail accreditation\SQ\Temperature\Logiciel Saisie des Etalonnages\Builds\V0.6\IHM\saisie_instrument.ui'
#
# Created: Sat May 17 03:24:39 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SaisieInstrument(object):
    def setupUi(self, SaisieInstrument):
        SaisieInstrument.setObjectName(_fromUtf8("SaisieInstrument"))
        SaisieInstrument.setWindowModality(QtCore.Qt.WindowModal)
        SaisieInstrument.resize(1013, 550)
        SaisieInstrument.setMinimumSize(QtCore.QSize(1013, 550))
        SaisieInstrument.setMaximumSize(QtCore.QSize(1013, 570))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        SaisieInstrument.setPalette(palette)
        SaisieInstrument.setStyleSheet(_fromUtf8("\n"
"QGroupBox {\n"
"background-color: rgb(225, 225, 225); \n"
"border: 1px solid Black;\n"
"border-radius: 5px;\n"
" margin-top: 1ex; /* leave space at the top for the title */\n"
" }\n"
"\n"
"QTextEdit{\n"
"background-color: rgb(225, 225, 225);\n"
"border: 1px solid Black;\n"
"border-radius: 5px;}\n"
"\n"
"QRadioButton{\n"
"background-color: rgb(225, 225, 225);}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(170, 255, 255);\n"
"border: 1px solid Black;\n"
"border-radius: 5px;\n"
"width: 130px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QComboBox {\n"
"background-color: rgb(225, 225, 225);\n"
"border: 1px solid Black;\n"
"border-radius: 5px;\n"
"padding: 1px 18px 1px 3px;}\n"
"\n"
"QLineEdit {\n"
"     border: 1px solid Black;\n"
"     border-radius: 5px;}\n"
"\n"
"\n"
"\n"
"QScrollBar {\n"
"    background-color: rgb(213, 213, 213);\n"
"}\n"
""))
        SaisieInstrument.setDockNestingEnabled(False)
        self.centralWidget = QtGui.QWidget(SaisieInstrument)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 190, 990, 122))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setEnabled(True)
        self.label_6.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 9, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_18.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 7, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_15.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 5, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setFrameShape(QtGui.QFrame.WinPanel)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.textEdit_n_serie = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_n_serie.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_n_serie.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_n_serie.setObjectName(_fromUtf8("textEdit_n_serie"))
        self.gridLayout.addWidget(self.textEdit_n_serie, 2, 4, 1, 1)
        self.textEdit_sap = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_sap.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_sap.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_sap.setObjectName(_fromUtf8("textEdit_sap"))
        self.gridLayout.addWidget(self.textEdit_sap, 2, 5, 1, 1)
        self.textEdit_identification = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_identification.setEnabled(False)
        self.textEdit_identification.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_identification.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_identification.setObjectName(_fromUtf8("textEdit_identification"))
        self.gridLayout.addWidget(self.textEdit_identification, 2, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.textEdit_commentaire = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_commentaire.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_commentaire.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_commentaire.setObjectName(_fromUtf8("textEdit_commentaire"))
        self.gridLayout.addWidget(self.textEdit_commentaire, 2, 7, 1, 1)
        self.textEdit_domaine_mesure = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_domaine_mesure.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_domaine_mesure.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_domaine_mesure.setObjectName(_fromUtf8("textEdit_domaine_mesure"))
        self.gridLayout.addWidget(self.textEdit_domaine_mesure, 2, 1, 1, 1)
        self.textEdit_famille = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_famille.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_famille.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_famille.setObjectName(_fromUtf8("textEdit_famille"))
        self.gridLayout.addWidget(self.textEdit_famille, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 6, 1, 1)
        self.textEdit_particularite = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_particularite.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_particularite.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_particularite.setObjectName(_fromUtf8("textEdit_particularite"))
        self.gridLayout.addWidget(self.textEdit_particularite, 2, 9, 1, 1)
        self.textEdit_resolution = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_resolution.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_resolution.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_resolution.setObjectName(_fromUtf8("textEdit_resolution"))
        self.gridLayout.addWidget(self.textEdit_resolution, 2, 6, 1, 1)
        self.textEdit_code = QtGui.QTextEdit(self.gridLayoutWidget)
        self.textEdit_code.setStyleSheet(_fromUtf8(""))
        self.textEdit_code.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_code.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_code.setObjectName(_fromUtf8("textEdit_code"))
        self.gridLayout.addWidget(self.textEdit_code, 2, 0, 1, 1)
        self.lineEdit_code = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_code.setEnabled(False)
        self.lineEdit_code.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_code.setText(_fromUtf8(""))
        self.lineEdit_code.setFrame(True)
        self.lineEdit_code.setObjectName(_fromUtf8("lineEdit_code"))
        self.gridLayout.addWidget(self.lineEdit_code, 3, 0, 1, 1)
        self.lineEdit_domain_mesure = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_domain_mesure.setEnabled(False)
        self.lineEdit_domain_mesure.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_domain_mesure.setText(_fromUtf8(""))
        self.lineEdit_domain_mesure.setFrame(True)
        self.lineEdit_domain_mesure.setObjectName(_fromUtf8("lineEdit_domain_mesure"))
        self.gridLayout.addWidget(self.lineEdit_domain_mesure, 3, 1, 1, 1)
        self.lineEdit_famille = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_famille.setEnabled(False)
        self.lineEdit_famille.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_famille.setText(_fromUtf8(""))
        self.lineEdit_famille.setFrame(True)
        self.lineEdit_famille.setObjectName(_fromUtf8("lineEdit_famille"))
        self.gridLayout.addWidget(self.lineEdit_famille, 3, 2, 1, 1)
        self.lineEdit_identification = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_identification.setEnabled(False)
        self.lineEdit_identification.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_identification.setText(_fromUtf8(""))
        self.lineEdit_identification.setFrame(True)
        self.lineEdit_identification.setObjectName(_fromUtf8("lineEdit_identification"))
        self.gridLayout.addWidget(self.lineEdit_identification, 3, 3, 1, 1)
        self.lineEdit_n_serie = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_n_serie.setEnabled(False)
        self.lineEdit_n_serie.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_n_serie.setText(_fromUtf8(""))
        self.lineEdit_n_serie.setFrame(True)
        self.lineEdit_n_serie.setObjectName(_fromUtf8("lineEdit_n_serie"))
        self.gridLayout.addWidget(self.lineEdit_n_serie, 3, 4, 1, 1)
        self.lineEdit_sap = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_sap.setEnabled(False)
        self.lineEdit_sap.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_sap.setText(_fromUtf8(""))
        self.lineEdit_sap.setFrame(True)
        self.lineEdit_sap.setObjectName(_fromUtf8("lineEdit_sap"))
        self.gridLayout.addWidget(self.lineEdit_sap, 3, 5, 1, 1)
        self.lineEdit_particularite = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_particularite.setEnabled(False)
        self.lineEdit_particularite.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_particularite.setText(_fromUtf8(""))
        self.lineEdit_particularite.setFrame(True)
        self.lineEdit_particularite.setObjectName(_fromUtf8("lineEdit_particularite"))
        self.gridLayout.addWidget(self.lineEdit_particularite, 3, 9, 1, 1)
        self.lineEdit_resolution = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_resolution.setEnabled(False)
        self.lineEdit_resolution.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_resolution.setText(_fromUtf8(""))
        self.lineEdit_resolution.setFrame(True)
        self.lineEdit_resolution.setObjectName(_fromUtf8("lineEdit_resolution"))
        self.gridLayout.addWidget(self.lineEdit_resolution, 3, 6, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 330, 991, 147))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setEnabled(True)
        self.label_12.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setEnabled(True)
        self.label_13.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_19.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 0, 5, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_20.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 0, 6, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_16.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 4, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_27.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_21.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 0, 7, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_23.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 0, 8, 1, 1)
        self.textEdit_duree_periodicite = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_duree_periodicite.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_duree_periodicite.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_duree_periodicite.setObjectName(_fromUtf8("textEdit_duree_periodicite"))
        self.gridLayout_2.addWidget(self.textEdit_duree_periodicite, 1, 6, 1, 1)
        self.textEdit_gestionnaire = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_gestionnaire.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_gestionnaire.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_gestionnaire.setObjectName(_fromUtf8("textEdit_gestionnaire"))
        self.gridLayout_2.addWidget(self.textEdit_gestionnaire, 1, 4, 1, 1)
        self.textEdit_localisation = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_localisation.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_localisation.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_localisation.setObjectName(_fromUtf8("textEdit_localisation"))
        self.gridLayout_2.addWidget(self.textEdit_localisation, 1, 3, 1, 1)
        self.textEdit_affectation = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_affectation.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_affectation.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_affectation.setObjectName(_fromUtf8("textEdit_affectation"))
        self.gridLayout_2.addWidget(self.textEdit_affectation, 1, 1, 1, 1)
        self.textEdit_site = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_site.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_site.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_site.setObjectName(_fromUtf8("textEdit_site"))
        self.gridLayout_2.addWidget(self.textEdit_site, 1, 0, 1, 1)
        self.textEdit_sous_affectation = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_sous_affectation.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_sous_affectation.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_sous_affectation.setObjectName(_fromUtf8("textEdit_sous_affectation"))
        self.gridLayout_2.addWidget(self.textEdit_sous_affectation, 1, 2, 1, 1)
        self.textEdit_etat_utilisation = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_etat_utilisation.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_etat_utilisation.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_etat_utilisation.setObjectName(_fromUtf8("textEdit_etat_utilisation"))
        self.gridLayout_2.addWidget(self.textEdit_etat_utilisation, 1, 8, 1, 1)
        self.textEdit_prestataire = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_prestataire.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_prestataire.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_prestataire.setObjectName(_fromUtf8("textEdit_prestataire"))
        self.gridLayout_2.addWidget(self.textEdit_prestataire, 1, 7, 1, 1)
        self.textEdit_periodicite = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_periodicite.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_periodicite.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_periodicite.setObjectName(_fromUtf8("textEdit_periodicite"))
        self.gridLayout_2.addWidget(self.textEdit_periodicite, 1, 5, 1, 1)
        self.lineEdit_site = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_site.setEnabled(False)
        self.lineEdit_site.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_site.setText(_fromUtf8(""))
        self.lineEdit_site.setFrame(True)
        self.lineEdit_site.setObjectName(_fromUtf8("lineEdit_site"))
        self.gridLayout_2.addWidget(self.lineEdit_site, 2, 0, 1, 1)
        self.lineEdit_affectation = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_affectation.setEnabled(False)
        self.lineEdit_affectation.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_affectation.setText(_fromUtf8(""))
        self.lineEdit_affectation.setFrame(True)
        self.lineEdit_affectation.setObjectName(_fromUtf8("lineEdit_affectation"))
        self.gridLayout_2.addWidget(self.lineEdit_affectation, 2, 1, 1, 1)
        self.lineEdit_periodicite = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_periodicite.setEnabled(False)
        self.lineEdit_periodicite.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_periodicite.setText(_fromUtf8(""))
        self.lineEdit_periodicite.setFrame(True)
        self.lineEdit_periodicite.setObjectName(_fromUtf8("lineEdit_periodicite"))
        self.gridLayout_2.addWidget(self.lineEdit_periodicite, 2, 5, 1, 1)
        self.lineEdit_gestionnaire = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_gestionnaire.setEnabled(False)
        self.lineEdit_gestionnaire.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_gestionnaire.setText(_fromUtf8(""))
        self.lineEdit_gestionnaire.setFrame(True)
        self.lineEdit_gestionnaire.setObjectName(_fromUtf8("lineEdit_gestionnaire"))
        self.gridLayout_2.addWidget(self.lineEdit_gestionnaire, 2, 4, 1, 1)
        self.lineEdit_prestataire = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_prestataire.setEnabled(False)
        self.lineEdit_prestataire.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_prestataire.setText(_fromUtf8(""))
        self.lineEdit_prestataire.setFrame(True)
        self.lineEdit_prestataire.setObjectName(_fromUtf8("lineEdit_prestataire"))
        self.gridLayout_2.addWidget(self.lineEdit_prestataire, 2, 7, 1, 1)
        self.lineEdit_duree_periodicite = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_duree_periodicite.setEnabled(False)
        self.lineEdit_duree_periodicite.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_duree_periodicite.setText(_fromUtf8(""))
        self.lineEdit_duree_periodicite.setFrame(True)
        self.lineEdit_duree_periodicite.setObjectName(_fromUtf8("lineEdit_duree_periodicite"))
        self.gridLayout_2.addWidget(self.lineEdit_duree_periodicite, 2, 6, 1, 1)
        self.lineEdit_sous_affectation = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_sous_affectation.setEnabled(False)
        self.lineEdit_sous_affectation.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_sous_affectation.setText(_fromUtf8(""))
        self.lineEdit_sous_affectation.setFrame(True)
        self.lineEdit_sous_affectation.setObjectName(_fromUtf8("lineEdit_sous_affectation"))
        self.gridLayout_2.addWidget(self.lineEdit_sous_affectation, 2, 2, 1, 1)
        self.lineEdit_localisation = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_localisation.setEnabled(False)
        self.lineEdit_localisation.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_localisation.setText(_fromUtf8(""))
        self.lineEdit_localisation.setFrame(True)
        self.lineEdit_localisation.setObjectName(_fromUtf8("lineEdit_localisation"))
        self.gridLayout_2.addWidget(self.lineEdit_localisation, 2, 3, 1, 1)
        self.lineEdit_etat_utilisation = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_etat_utilisation.setEnabled(False)
        self.lineEdit_etat_utilisation.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lineEdit_etat_utilisation.setText(_fromUtf8(""))
        self.lineEdit_etat_utilisation.setFrame(True)
        self.lineEdit_etat_utilisation.setObjectName(_fromUtf8("lineEdit_etat_utilisation"))
        self.gridLayout_2.addWidget(self.lineEdit_etat_utilisation, 2, 8, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralWidget)
        self.buttonBox.setGeometry(QtCore.QRect(680, 500, 311, 43))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(100, 0))
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.buttonBox.setBaseSize(QtCore.QSize(16, 0))
        self.buttonBox.setStatusTip(_fromUtf8(""))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Abort|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 991, 171))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_25 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtGui.QPixmap(_fromUtf8("LOGO_REACTUALISE_petit_format.png")))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_8.addWidget(self.label_25)
        self.calendarWidget_2 = QtGui.QCalendarWidget(self.horizontalLayoutWidget_2)
        self.calendarWidget_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.calendarWidget_2.setObjectName(_fromUtf8("calendarWidget_2"))
        self.horizontalLayout_8.addWidget(self.calendarWidget_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_26 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_10.addWidget(self.label_26)
        self.groupBox_2 = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.groupBox_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 0, 82, 17))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(160, 0, 82, 17))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.horizontalLayout_10.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_28 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_28.setMinimumSize(QtCore.QSize(235, 0))
        self.label_28.setMaximumSize(QtCore.QSize(235, 16777215))
        self.label_28.setStyleSheet(_fromUtf8(""))
        self.label_28.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_11.addWidget(self.label_28)
        self.spinBox_nbr_instrum_2 = QtGui.QSpinBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_nbr_instrum_2.sizePolicy().hasHeightForWidth())
        self.spinBox_nbr_instrum_2.setSizePolicy(sizePolicy)
        self.spinBox_nbr_instrum_2.setMinimumSize(QtCore.QSize(234, 0))
        self.spinBox_nbr_instrum_2.setMaximumSize(QtCore.QSize(234, 16777215))
        self.spinBox_nbr_instrum_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_nbr_instrum_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_nbr_instrum_2.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinBox_nbr_instrum_2.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.spinBox_nbr_instrum_2.setMinimum(1)
        self.spinBox_nbr_instrum_2.setObjectName(_fromUtf8("spinBox_nbr_instrum_2"))
        self.horizontalLayout_11.addWidget(self.spinBox_nbr_instrum_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_29 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_29.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_29.setFrameShadow(QtGui.QFrame.Plain)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_12.addWidget(self.label_29)
        self.comboBox_ref_constructeur_2 = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_ref_constructeur_2.setEnabled(True)
        self.comboBox_ref_constructeur_2.setEditable(True)
        self.comboBox_ref_constructeur_2.setObjectName(_fromUtf8("comboBox_ref_constructeur_2"))
        self.horizontalLayout_12.addWidget(self.comboBox_ref_constructeur_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_30 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_13.addWidget(self.label_30)
        self.comboBox_constructeur_2 = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_constructeur_2.setEditable(True)
        self.comboBox_constructeur_2.setObjectName(_fromUtf8("comboBox_constructeur_2"))
        self.horizontalLayout_13.addWidget(self.comboBox_constructeur_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_31 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_14.addWidget(self.label_31)
        self.comboBox_designation_2 = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_designation_2.setEditable(True)
        self.comboBox_designation_2.setObjectName(_fromUtf8("comboBox_designation_2"))
        self.horizontalLayout_14.addWidget(self.comboBox_designation_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_32 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_15.addWidget(self.label_32)
        self.comboBox_statut_2 = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_statut_2.setEditable(True)
        self.comboBox_statut_2.setObjectName(_fromUtf8("comboBox_statut_2"))
        self.comboBox_statut_2.addItem(_fromUtf8(""))
        self.comboBox_statut_2.addItem(_fromUtf8(""))
        self.comboBox_statut_2.addItem(_fromUtf8(""))
        self.comboBox_statut_2.addItem(_fromUtf8(""))
        self.comboBox_statut_2.addItem(_fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.comboBox_statut_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_8)
        SaisieInstrument.setCentralWidget(self.centralWidget)

        self.retranslateUi(SaisieInstrument)
        QtCore.QObject.connect(self.radioButton_3, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.textEdit_identification.setDisabled)
        QtCore.QObject.connect(self.radioButton_4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.textEdit_identification.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SaisieInstrument)
        SaisieInstrument.setTabOrder(self.textEdit_code, self.textEdit_domaine_mesure)
        SaisieInstrument.setTabOrder(self.textEdit_domaine_mesure, self.textEdit_famille)
        SaisieInstrument.setTabOrder(self.textEdit_famille, self.textEdit_identification)
        SaisieInstrument.setTabOrder(self.textEdit_identification, self.textEdit_n_serie)
        SaisieInstrument.setTabOrder(self.textEdit_n_serie, self.textEdit_sap)
        SaisieInstrument.setTabOrder(self.textEdit_sap, self.textEdit_resolution)
        SaisieInstrument.setTabOrder(self.textEdit_resolution, self.textEdit_commentaire)
        SaisieInstrument.setTabOrder(self.textEdit_commentaire, self.textEdit_particularite)
        SaisieInstrument.setTabOrder(self.textEdit_particularite, self.textEdit_site)
        SaisieInstrument.setTabOrder(self.textEdit_site, self.textEdit_affectation)
        SaisieInstrument.setTabOrder(self.textEdit_affectation, self.textEdit_sous_affectation)
        SaisieInstrument.setTabOrder(self.textEdit_sous_affectation, self.textEdit_localisation)
        SaisieInstrument.setTabOrder(self.textEdit_localisation, self.textEdit_gestionnaire)
        SaisieInstrument.setTabOrder(self.textEdit_gestionnaire, self.textEdit_periodicite)
        SaisieInstrument.setTabOrder(self.textEdit_periodicite, self.textEdit_duree_periodicite)
        SaisieInstrument.setTabOrder(self.textEdit_duree_periodicite, self.textEdit_prestataire)
        SaisieInstrument.setTabOrder(self.textEdit_prestataire, self.textEdit_etat_utilisation)
        SaisieInstrument.setTabOrder(self.textEdit_etat_utilisation, self.buttonBox)
        SaisieInstrument.setTabOrder(self.buttonBox, self.lineEdit_sap)
        SaisieInstrument.setTabOrder(self.lineEdit_sap, self.lineEdit_particularite)
        SaisieInstrument.setTabOrder(self.lineEdit_particularite, self.lineEdit_site)
        SaisieInstrument.setTabOrder(self.lineEdit_site, self.lineEdit_affectation)
        SaisieInstrument.setTabOrder(self.lineEdit_affectation, self.lineEdit_periodicite)
        SaisieInstrument.setTabOrder(self.lineEdit_periodicite, self.lineEdit_gestionnaire)
        SaisieInstrument.setTabOrder(self.lineEdit_gestionnaire, self.lineEdit_prestataire)
        SaisieInstrument.setTabOrder(self.lineEdit_prestataire, self.lineEdit_duree_periodicite)
        SaisieInstrument.setTabOrder(self.lineEdit_duree_periodicite, self.lineEdit_sous_affectation)
        SaisieInstrument.setTabOrder(self.lineEdit_sous_affectation, self.lineEdit_localisation)
        SaisieInstrument.setTabOrder(self.lineEdit_localisation, self.lineEdit_etat_utilisation)
        SaisieInstrument.setTabOrder(self.lineEdit_etat_utilisation, self.lineEdit_domain_mesure)
        SaisieInstrument.setTabOrder(self.lineEdit_domain_mesure, self.lineEdit_famille)
        SaisieInstrument.setTabOrder(self.lineEdit_famille, self.lineEdit_code)
        SaisieInstrument.setTabOrder(self.lineEdit_code, self.lineEdit_identification)
        SaisieInstrument.setTabOrder(self.lineEdit_identification, self.lineEdit_n_serie)
        SaisieInstrument.setTabOrder(self.lineEdit_n_serie, self.lineEdit_resolution)

    def retranslateUi(self, SaisieInstrument):
        SaisieInstrument.setWindowTitle(_translate("SaisieInstrument", "Saisie instrument(s)", None))
        self.label_6.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Particularite</p></body></html>", None))
        self.label_18.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Commentaire</p></body></html>", None))
        self.label_2.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Code</p></body></html>", None))
        self.label_14.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">N_Serie</p></body></html>", None))
        self.label_15.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">N_SAP</p></body></html>", None))
        self.label.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Identification</p></body></html>", None))
        self.label_3.setText(_translate("SaisieInstrument", "Domaine de mesure", None))
        self.label_4.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Famille</p></body></html>", None))
        self.label_10.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Resolution</p></body></html>", None))
        self.label_12.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Sous </p><p align=\"center\">Affectation</p></body></html>", None))
        self.label_13.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Localisation</p></body></html>", None))
        self.label_19.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Periodicite</p></body></html>", None))
        self.label_20.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Periodicite </p><p align=\"center\">(mois/annee)</p></body></html>", None))
        self.label_11.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Affectation</p></body></html>", None))
        self.label_16.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Gestionnaire</p></body></html>", None))
        self.label_27.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Site</p></body></html>", None))
        self.label_21.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Prestataire</p></body></html>", None))
        self.label_23.setText(_translate("SaisieInstrument", "<html><head/><body><p align=\"center\">Etat d\'utilisation</p></body></html>", None))
        self.label_26.setText(_translate("SaisieInstrument", "Identification Instrument", None))
        self.radioButton_3.setText(_translate("SaisieInstrument", "Automatique", None))
        self.radioButton_4.setText(_translate("SaisieInstrument", "Manuelle", None))
        self.label_28.setText(_translate("SaisieInstrument", "<html><head/><body><p>Nbr d\'instrument à créer</p></body></html>", None))
        self.label_29.setText(_translate("SaisieInstrument", "<html><head/><body><p>Reference Constructeur</p></body></html>", None))
        self.label_30.setText(_translate("SaisieInstrument", "Constructeur", None))
        self.label_31.setText(_translate("SaisieInstrument", "Designation", None))
        self.label_32.setText(_translate("SaisieInstrument", "Satut ", None))
        self.comboBox_statut_2.setItemText(0, _translate("SaisieInstrument", "Instrument de mesure", None))
        self.comboBox_statut_2.setItemText(1, _translate("SaisieInstrument", "Etalon de Reference", None))
        self.comboBox_statut_2.setItemText(2, _translate("SaisieInstrument", "Etalon de Travail", None))
        self.comboBox_statut_2.setItemText(3, _translate("SaisieInstrument", "Etalon Voyageur", None))
        self.comboBox_statut_2.setItemText(4, _translate("SaisieInstrument", "Generateur", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SaisieInstrument = QtGui.QMainWindow()
    ui = Ui_SaisieInstrument()
    ui.setupUi(SaisieInstrument)
    SaisieInstrument.show()
    sys.exit(app.exec_())

